title: Srikar Gudipati
email: srikarvgudipati@gmail.com
description: "The internet home of Srikar Gudipati."

twitter: srikarg_
facebook: srikar.gudipati
linkedin: srikargudipati
email: srikarvgudipati@gmail.com

gems: [jekyll-paginate, jekyll-coffeescript]
markdown_ext: md

permalink: "/blog/:title"

paginate: 5
paginate_path: "/blog/page:num"
