name: "Srikar Gudipati"
author: "Srikar Gudipati"
description: "My personal website/blog!"

markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "disable_indented_code_blocks", "space_after_headers", "with_toc_data"]
markdown_ext: md

permalink: "/blog/:title"
pygments: true

paginate: 7
paginate_path: "/page/:num"

exclude: ['node_modules', 'gulpfile.js', 'src']
