name: "Srikar Gudipati"
author: "Srikar Gudipati"
description: "My personal website/blog!"

markdown: redcarpet
redcarpet:
  extensions: [with_toc_data]
permalink: "/blog/:title"
pygments: true

paginate: 7
paginate_path: "/page/:num"

exclude: ['node_modules', 'gulpfile.js', 'src']
