name: "Srikar Gudipati"
description: "My personal website."
url: "http://localhost:4000"

auto: true;
server: true;
exclude: ['README.md']

paginate: 7

markdown: rdiscount
permalink: /blog/:title
pygments: true