title: Srikar Gudipati
email: srikarvgudipati@gmail.com
description: "The internet home of Srikar Gudipati."

twitter: srikarg_
facebook: srikar.gudipati
linkedin: srikargudipati
email: srikarvgudipati@gmail.com

gems: [jekyll-paginate, jekyll-coffeescript]
markdown: redcarpet
markdown_ext: md
redcarpet:
    extensions: ["fenced_code_blocks", "disable_indented_code_blocks", "space_after_headers", "with_toc_data"]

permalink: "/blog/:title"

paginate: 5
paginate_path: "/blog/page:num"
